version: '3.9'
services:

  # nginx server
  nginx:
    build: ./backend/nginx
    container_name: server
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes: 
      - ./secret/certs:/etc/nginx/certs:ro

  # main django api app run on gunicorn
  api:
    build: .
    container_name: api
    command: > 
      /bin/sh -c "python manage.py makemigrations
                  python manage.py migrate
                  gunicorn -c backend/gunicorn/dev.py"
    expose:
      - 8000
    restart: unless-stopped
  
  # message passing interface
  redis:
    image: redis:alpine
    container_name: redis
    restart: always # unless-stopped ?
  
  # tasking interface worker
  celery_worker:
    build: .
    container_name: celery-worker
    command: celery -A backend worker -l INFO
    restart: unless-stopped
  
  # tasking interface scheduler
  celery_beat:
    build: .
    container_name: celery-beat
    command: celery -A backend beat -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler
    restart: unless-stopped