# Generated by Django 4.0.5 on 2022-06-28 00:58

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AverageSolvingTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_type_id', models.SmallIntegerField()),
                ('avg_solving_time_hours', models.FloatField()),
            ],
            options={
                'db_table': 'history"."api_v1_average_solving_time',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticket_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('ticket_type_id', models.SmallIntegerField(default=1)),
                ('server_id', models.CharField(max_length=100)),
                ('client_id', models.CharField(max_length=100)),
                ('issue_date', models.DateTimeField()),
                ('solving_date', models.DateTimeField(blank=True, null=True)),
                ('ticket_status_id', models.SmallIntegerField(default=1)),
                ('hours_in_pause', models.FloatField(blank=True, default=0.0, null=True)),
                ('last_pause_timestamp', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'history"."api_v1_ticket_global',
            },
        ),
        migrations.CreateModel(
            name='TicketStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_status_id', models.SmallIntegerField()),
                ('ticket_status', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'static"."api_v1_ticket_status',
            },
        ),
        migrations.CreateModel(
            name='TicketType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_type_id', models.SmallIntegerField()),
                ('ticket_type', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'static"."api_v1_ticket_type',
            },
        ),
        migrations.CreateModel(
            name='OutgoingAccountPayment',
            fields=[
                ('ticket_assigned', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api_v1.ticket')),
                ('payment_amount', models.FloatField()),
                ('clearing_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'history"."api_v1_outgoing_account_payment',
            },
        ),
        migrations.CreateModel(
            name='OutgoingAccountPaymentTransfer',
            fields=[
                ('ticket_assigned', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api_v1.ticket')),
                ('payment_amount', models.FloatField()),
                ('clearing_time', models.DateTimeField(blank=True)),
            ],
            options={
                'db_table': 'history"."api_v1_outgoing_account_payment_transfer',
            },
        ),
        migrations.CreateModel(
            name='TurnoverLimitAlert',
            fields=[
                ('ticket_assigned', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api_v1.ticket')),
                ('account_type', models.CharField(max_length=100)),
                ('legal_country_code', models.CharField(max_length=20)),
                ('legal_entity_type', models.CharField(blank=True, max_length=50, null=True)),
                ('limit_type', models.CharField(max_length=50)),
                ('limit_product', models.CharField(max_length=50)),
                ('limit_entity', models.CharField(max_length=50)),
                ('limit_percentage', models.FloatField()),
                ('limit_amount', models.FloatField()),
                ('turnover_last_thirty_days', models.FloatField()),
                ('turnover_prev_thirty_days', models.FloatField()),
                ('limit_due_date', models.DateTimeField()),
                ('brands', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True, size=None)),
                ('channels', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True, size=None)),
                ('terminals', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True, size=None)),
                ('currencies', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True, size=None)),
            ],
            options={
                'db_table': 'history"."api_v1_turnover_limit_alert',
            },
        ),
        migrations.CreateModel(
            name='UnverifiedPaymentSource',
            fields=[
                ('ticket_assigned', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api_v1.ticket')),
                ('payment_amount', models.FloatField()),
                ('currencies', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), blank=True, null=True, size=None)),
            ],
            options={
                'db_table': 'history"."api_v1_unverified_payment_source',
            },
        ),
        migrations.CreateModel(
            name='VerifyProfile',
            fields=[
                ('ticket_assigned', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api_v1.ticket')),
                ('scoring_type', models.CharField(max_length=100)),
                ('account_type', models.CharField(max_length=100)),
                ('legal_country_code', models.CharField(max_length=20)),
                ('legal_entity_type', models.CharField(blank=True, max_length=50, null=True)),
                ('profile_bank_accounts', models.IntegerField(default=0)),
                ('enabled_currencies', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), blank=True, null=True, size=None)),
                ('brands', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True, size=None)),
            ],
            options={
                'db_table': 'history"."api_v1_verify_profile',
            },
        ),
        migrations.CreateModel(
            name='ScoringGlobal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('timestamp', models.DateTimeField()),
                ('ticket_assigned', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api_v1.ticket')),
            ],
            options={
                'db_table': 'history"."api_v1_scoring_global',
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_local_id', models.CharField(max_length=100)),
                ('average_fee_rate', models.FloatField()),
                ('account_category_type', models.IntegerField()),
                ('specified_turnover_current', models.FloatField(blank=True, null=True)),
                ('specified_turnover_in_3_m', models.FloatField(blank=True, null=True)),
                ('specified_turnover_in_6_m', models.FloatField(blank=True, null=True)),
                ('specified_turnover_in_12_m', models.FloatField(blank=True, null=True)),
                ('ticket_assigned', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api_v1.ticket')),
            ],
            options={
                'db_table': 'history"."api_v1_brand',
            },
        ),
    ]
