# Generated by Django 4.0.5 on 2022-06-10 15:09

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.CharField(max_length=100)),
                ('brand_local_id', models.CharField(max_length=100)),
                ('average_fee_rate', models.FloatField()),
                ('account_category_type', models.IntegerField()),
                ('specified_turnover_current', models.FloatField(blank=True)),
                ('specified_turnover_in_3_m', models.FloatField(blank=True)),
                ('specified_turnover_in_6_m', models.FloatField(blank=True)),
                ('specified_turnover_in_12_m', models.FloatField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.CharField(max_length=100)),
                ('server_id', models.CharField(max_length=100)),
                ('client_id', models.CharField(max_length=100)),
                ('ticket_issue_date', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TurnoverLimitAlert',
            fields=[
                ('ticket_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api_v1.ticket')),
                ('amount', models.FloatField()),
            ],
            bases=('api_v1.ticket',),
        ),
        migrations.CreateModel(
            name='UnverifiedPaySource',
            fields=[
                ('ticket_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api_v1.ticket')),
                ('amount', models.FloatField()),
            ],
            bases=('api_v1.ticket',),
        ),
        migrations.CreateModel(
            name='VerifyProfile',
            fields=[
                ('ticket_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api_v1.ticket')),
                ('scoring_type', models.CharField(max_length=100)),
                ('account_type', models.CharField(max_length=100)),
                ('legal_country_code', models.CharField(max_length=20)),
                ('legal_entity_type', models.CharField(blank=True, max_length=50)),
                ('profile_bank_accounts', models.IntegerField()),
                ('enabled_currencies', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), blank=True, size=None)),
            ],
            bases=('api_v1.ticket',),
        ),
    ]
