# Generated by Django 4.0.5 on 2022-06-24 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AverageSolvingTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_type_id', models.SmallIntegerField()),
                ('avg_solving_time_hours', models.FloatField()),
            ],
            options={
                'db_table': 'history"."api_v1_average_solving_time',
            },
        ),
    ]
